greeting: "안녕하세요"
spring:
  profiles: local
greeting: "Local 서버"
# jdbc:
#   driverClassName: net.sf.log4jdbc.DriverSpy
#   url: jdbc:log4jdbc:postgresql://localhost:5432/sdb
#   username: postgres
#   password: addad
